In [25]:
import pandas as pd
import numpy as np
import random

In [55]:
random.seed(123)
n = 3
m = 8
a = np.random.randint(low = 1,
                     high=100,
                     size = (n,m))
a

array([[18, 24, 46, 40,  7, 18, 38, 82],
       [20, 97, 32, 32, 90, 14, 57, 70],
       [53, 64, 12, 63,  9, 50, 60, 46]])

In [56]:
a.sort(axis = 1)

In [57]:
# bottom 中最da值最大值 
# top中 最xiao值最小值

In [58]:
a

array([[ 7, 18, 18, 24, 38, 40, 46, 82],
       [14, 20, 32, 32, 57, 70, 90, 97],
       [ 9, 12, 46, 50, 53, 60, 63, 64]])

In [59]:
b = list(a.reshape(1,-1)[0])
b.sort()
b

[7,
 9,
 12,
 14,
 18,
 18,
 20,
 24,
 32,
 32,
 38,
 40,
 46,
 46,
 50,
 53,
 57,
 60,
 63,
 64,
 70,
 82,
 90,
 97]

In [60]:
b[round(n*m/2)]

46

In [63]:
(a > 55).sum(axis = 1) >= 4

array([False,  True, False])

In [ ]:
说明第一行和第三行没有满足m/2

In [9]:
# The smallest in Top m/2 
a[:,2]
# choose 

array([23,  8, 50])

In [36]:
# The biggest in Bottom m/2
a[:, 1]

array([1, 1, 2])

In [ ]:
# -x----x-----[x------------0]-------0--------0------