In [1]:
import pandas as pd
import numpy as np
import random

ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/usr/local/bin/python3"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))


In [1]:
random.seed(123)
n = 3
m = 8
a = np.random.randint(low = 1,
                     high=100,
                     size = (n,m))
a

NameError: name 'random' is not defined

In [ ]:
import math

def check_valid(i, cur_win, cost, win_len, arr):
    cur_min = min(cur_win)
    cur_max = max(cur_win)
    valid = True

    selected = []
    for k in range(i+1,n):
        cur_list = []
        cur_list.append(cur_win)
        for j in range(m):
            if cur_min < arr[k][j] < cur_max:
                cur_list.append(arr[k][j])
        if len(cur_list) < win_len:
            valid = False
            break
        selected.append(cur_list)
    
    if valid and (cur_max - cur_min) < cost:
        cost = (cur_max - cur_min)
        return cost, selected
    else:
        return cost, []
        

def getMaxProduct(arr):
    n, m = len(arr), len(arr[0])
    win_len = m/2
    
    for i in range(n):
        arr[i].sort()

    cost = float('inf')
    i = 0
    j = 0
    while i < n:
        while j < win_len:
            cur_win = arr[i][j:j+win_len+1]
            cost, temp_select = check_valid(i, cur_win, cost, win_len, arr)
            if temp_select != 0:
                for k in range(win_len+1,m):
                    if arr[i][k] - arr[i][j] < cost:
                        cost = arr[i][k] - arr[i][j]
                        for l in range(i+1,n):
                            max_inx = np.argmax(temp_select[l][-1])
                            for p in range(max_inx,m):
                                if arr[l][p] > arr[i][k]:
                                    temp_select[l].append(arr[l][p])
            selected = temp_select
            j += 1
        i += 1
    return cost * (np.shape(selected)[0] * np.shape(selected)[1])




In [56]:
a.sort(axis = 1)

In [57]:
# bottom 中最da值最大值 
# top中 最xiao值最小值

In [58]:
a

array([[ 7, 18, 18, 24, 38, 40, 46, 82],
       [14, 20, 32, 32, 57, 70, 90, 97],
       [ 9, 12, 46, 50, 53, 60, 63, 64]])

In [59]:
b = list(a.reshape(1,-1)[0])
b.sort()
b

[7,
 9,
 12,
 14,
 18,
 18,
 20,
 24,
 32,
 32,
 38,
 40,
 46,
 46,
 50,
 53,
 57,
 60,
 63,
 64,
 70,
 82,
 90,
 97]

In [60]:
b[round(n*m/2)]

46

In [99]:
p = 0
q = n*m-1
checked = True
while q - p >= m*n/2 and checked:
    
    q_next = q-1
    p_next = p+1
    left_dif = b[q] - b[q_next]
    right_dif = b[p_next] - b[p]

    if left_dif <= right_dif and sum(((a >= b[p])*(a <= b[q_next])).sum(axis = 1) >= m/2) == n:
        q = q_next
        print(f'p:{p}, q:{q}')
    elif left_dif > right_dif and sum(((a >= b[p_next])*(a <= b[q])).sum(axis = 1) >= m/2) == n:
        p = p_next
    else:
        checked = False
    print(f'p:{p}, q:{q}')
    print(checked)
    print("=============\n")

p:1, q:23
True

p:2, q:23
True

p:3, q:23
True

p:4, q:23
True

p:5, q:23
True

p:6, q:23
True

p:7, q:23
True

p:7, q:22
p:7, q:22
True

p:7, q:21
p:7, q:21
True

p:8, q:21
True

p:9, q:21
True

p:9, q:21
False



In [104]:
(b[21]-b[9])*(4+4+6)

700

In [105]:
14*(70-24)

644

In [102]:
a

array([[ 7, 18, 18, 24, 38, 40, 46, 82],
       [14, 20, 32, 32, 57, 70, 90, 97],
       [ 9, 12, 46, 50, 53, 60, 63, 64]])

In [90]:
print(f'p:{p}, q:{q}')

0, 24


In [71]:
a

array([[ 7, 18, 18, 24, 38, 40, 46, 82],
       [14, 20, 32, 32, 57, 70, 90, 97],
       [ 9, 12, 46, 50, 53, 60, 63, 64]])

n

In [77]:
p = 55
q = 80
sum(((a >= p)*(a <= 80)).sum(axis = 1) >= m/2) == n

False

In [ ]:
说明第一行和第三行没有满足m/2

In [9]:
# The smallest in Top m/2 
a[:,2]
# choose 

array([23,  8, 50])

In [36]:
# The biggest in Bottom m/2
a[:, 1]

array([1, 1, 2])

In [ ]:
# -x----x-----[x------------0]-------0--------0------