In [25]:
import pandas as pd
import numpy as np
import random

In [55]:
random.seed(123)
n = 3
m = 8
a = np.random.randint(low = 1,
                     high=100,
                     size = (n,m))
a

array([[18, 24, 46, 40,  7, 18, 38, 82],
       [20, 97, 32, 32, 90, 14, 57, 70],
       [53, 64, 12, 63,  9, 50, 60, 46]])

In [56]:
a.sort(axis = 1)

In [57]:
# bottom 中最da值最大值 
# top中 最xiao值最小值

In [58]:
a

array([[ 7, 18, 18, 24, 38, 40, 46, 82],
       [14, 20, 32, 32, 57, 70, 90, 97],
       [ 9, 12, 46, 50, 53, 60, 63, 64]])

In [59]:
b = list(a.reshape(1,-1)[0])
b.sort()
b

[7,
 9,
 12,
 14,
 18,
 18,
 20,
 24,
 32,
 32,
 38,
 40,
 46,
 46,
 50,
 53,
 57,
 60,
 63,
 64,
 70,
 82,
 90,
 97]

In [60]:
b[round(n*m/2)]

46

In [99]:
p = 0
q = n*m-1
checked = True
while q - p >= m*n/2 and checked:
    
    q_next = q-1
    p_next = p+1
    left_dif = b[q] - b[q_next]
    right_dif = b[p_next] - b[p]

    if left_dif <= right_dif and sum(((a >= b[p])*(a <= b[q_next])).sum(axis = 1) >= m/2) == n:
        q = q_next
        print(f'p:{p}, q:{q}')
    elif left_dif > right_dif and sum(((a >= b[p_next])*(a <= b[q])).sum(axis = 1) >= m/2) == n:
        p = p_next
    else:
        checked = False
    print(f'p:{p}, q:{q}')
    print(checked)
    print("=============\n")

p:1, q:23
True

p:2, q:23
True

p:3, q:23
True

p:4, q:23
True

p:5, q:23
True

p:6, q:23
True

p:7, q:23
True

p:7, q:22
p:7, q:22
True

p:7, q:21
p:7, q:21
True

p:8, q:21
True

p:9, q:21
True

p:9, q:21
False



In [104]:
(b[21]-b[9])*(4+4+6)

700

In [105]:
14*(70-24)

644

In [102]:
a

array([[ 7, 18, 18, 24, 38, 40, 46, 82],
       [14, 20, 32, 32, 57, 70, 90, 97],
       [ 9, 12, 46, 50, 53, 60, 63, 64]])

In [90]:
print(f'p:{p}, q:{q}')

0, 24


In [71]:
a

array([[ 7, 18, 18, 24, 38, 40, 46, 82],
       [14, 20, 32, 32, 57, 70, 90, 97],
       [ 9, 12, 46, 50, 53, 60, 63, 64]])

n

In [77]:
p = 55
q = 80
sum(((a >= p)*(a <= 80)).sum(axis = 1) >= m/2) == n

False

In [ ]:
说明第一行和第三行没有满足m/2

In [9]:
# The smallest in Top m/2 
a[:,2]
# choose 

array([23,  8, 50])

In [36]:
# The biggest in Bottom m/2
a[:, 1]

array([1, 1, 2])

In [ ]:
# -x----x-----[x------------0]-------0--------0------