In [1]:
import pandas as pd
import numpy as np
import random

In [6]:
import math

def getMaxProduct0(arr):
    n, m = len(arr), len(arr[0])
    lo, hi = 0, max(max(row) for row in arr) - min(min(row) for row in arr)
    while lo < hi:
        mid = (lo + hi) // 2
        max_cnt = 0
        for row in arr:
            cnt = 0
            l, r = 0, math.ceil(m / 2)
            window_sum = sum(row[l:r])
            while r <= m:
                if window_sum <= mid:
                    cnt = r - l
                    l += 1
                    r += 1
                    window_sum += row[r-1] - row[l-1]
                else:
                    window_sum -= row[l] - row[l-1]
                    l += 1
            max_cnt = max(max_cnt, cnt)
        if max_cnt >= math.ceil(m / 2):
            lo = mid + 1
        else:
            hi = mid
    return lo * max_cnt

def getMaxProduct1(arr):
    n = len(arr)
    m = len(arr[0])
    
    # 先将每行的数据排序，然后计算排序后中间的一段数据的最小值，用于求解最小代价
    for i in range(n):
        arr[i].sort()
        
    # 初始代价设为正无穷大
    cost = float('inf')
    # 枚举第一个数字和第二个数字，计算每个数字作为最小值时的代价
    for i in range(m):
        for j in range(i+1, m):
            # 对于每个数字作为最小值时，计算这个数字所在列的代价
            col = [arr[k][i:j+1] for k in range(n)]
            col_min = [min(row) for row in col]
            col_max = max(col_min)
            cost = min(cost, col_max - min(col_min))
    
    # 计算最小代价的个数
    cnt = (n * m + m) // 2
    
    # 计算最大乘积
    max_product = cost * cnt
    return max_product


In [2]:
# random.seed(123)
# n = 3
# m = 8
# a = np.random.randint(low = 1,
#                      high=100,
#                      size = (n,m))
# a

array([[57, 29, 61, 45, 30, 85, 87, 61],
       [97, 77, 52, 10, 58, 53, 97, 96],
       [87, 56, 65, 95, 74, 51, 57, 79]])

In [11]:
a = np.array([[ 7, 18, 18, 24, 38, 40, 46, 82],
       [14, 20, 32, 32, 57, 70, 90, 97],
       [ 9, 12, 46, 50, 53, 60, 63, 64]])
a.shape

(3, 8)

In [12]:
a

array([[ 7, 18, 18, 24, 38, 40, 46, 82],
       [14, 20, 32, 32, 57, 70, 90, 97],
       [ 9, 12, 46, 50, 53, 60, 63, 64]])

In [7]:
getMaxProduct(a)

IndexError: index 8 is out of bounds for axis 0 with size 8

In [3]:
a.sort(axis = 1)

In [4]:
# bottom 中最da值最大值 
# top中 最xiao值最小值

In [5]:
a

array([[29, 30, 45, 57, 61, 61, 85, 87],
       [10, 52, 53, 58, 77, 96, 97, 97],
       [51, 56, 57, 65, 74, 79, 87, 95]])

In [59]:
b = list(a.reshape(1,-1)[0])
b.sort()
b

[7,
 9,
 12,
 14,
 18,
 18,
 20,
 24,
 32,
 32,
 38,
 40,
 46,
 46,
 50,
 53,
 57,
 60,
 63,
 64,
 70,
 82,
 90,
 97]

In [60]:
b[round(n*m/2)]

46

In [99]:
p = 0
q = n*m-1
checked = True
while q - p >= m*n/2 and checked:
    
    q_next = q-1
    p_next = p+1
    left_dif = b[q] - b[q_next]
    right_dif = b[p_next] - b[p]

    if left_dif <= right_dif and sum(((a >= b[p])*(a <= b[q_next])).sum(axis = 1) >= m/2) == n:
        q = q_next
        print(f'p:{p}, q:{q}')
    elif left_dif > right_dif and sum(((a >= b[p_next])*(a <= b[q])).sum(axis = 1) >= m/2) == n:
        p = p_next
    else:
        checked = False
    print(f'p:{p}, q:{q}')
    print(checked)
    print("=============\n")

p:1, q:23
True

p:2, q:23
True

p:3, q:23
True

p:4, q:23
True

p:5, q:23
True

p:6, q:23
True

p:7, q:23
True

p:7, q:22
p:7, q:22
True

p:7, q:21
p:7, q:21
True

p:8, q:21
True

p:9, q:21
True

p:9, q:21
False



In [104]:
(b[21]-b[9])*(4+4+6)

700

In [105]:
14*(70-24)

644

In [102]:
a

array([[ 7, 18, 18, 24, 38, 40, 46, 82],
       [14, 20, 32, 32, 57, 70, 90, 97],
       [ 9, 12, 46, 50, 53, 60, 63, 64]])

In [90]:
print(f'p:{p}, q:{q}')

0, 24


In [71]:
a

array([[ 7, 18, 18, 24, 38, 40, 46, 82],
       [14, 20, 32, 32, 57, 70, 90, 97],
       [ 9, 12, 46, 50, 53, 60, 63, 64]])

n

In [77]:
p = 55
q = 80
sum(((a >= p)*(a <= 80)).sum(axis = 1) >= m/2) == n

False

In [ ]:
说明第一行和第三行没有满足m/2

In [9]:
# The smallest in Top m/2 
a[:,2]
# choose 

array([23,  8, 50])

In [36]:
# The biggest in Bottom m/2
a[:, 1]

array([1, 1, 2])

In [ ]:
#  -x----x-----x--------p----0-------0---q-----0------  